
package net.restfulwebservices.servicecontracts._2008._01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import net.restfulwebservices.datacontracts._2008._01.Weather;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWeatherForecastService", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    faultcontracts.gotlservices._2008._01.ObjectFactory.class,
    net.restfulwebservices.datacontracts._2008._01.ObjectFactory.class,
    net.restfulwebservices.servicecontracts._2008._01.ObjectFactory.class
})
public interface IWeatherForecastService {


    /**
     * 
     * @param country
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     * @throws IWeatherForecastServiceGetCitiesByCountryDefaultFaultContractFaultFaultMessage
     */
    @WebMethod(operationName = "GetCitiesByCountry", action = "GetCitiesByCountry")
    @WebResult(name = "GetCitiesByCountryResult", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
    @RequestWrapper(localName = "GetCitiesByCountry", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "net.restfulwebservices.servicecontracts._2008._01.GetCitiesByCountry")
    @ResponseWrapper(localName = "GetCitiesByCountryResponse", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "net.restfulwebservices.servicecontracts._2008._01.GetCitiesByCountryResponse")
    public ArrayOfstring getCitiesByCountry(
        @WebParam(name = "Country", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
        String country)
        throws IWeatherForecastServiceGetCitiesByCountryDefaultFaultContractFaultFaultMessage
    ;

    /**
     * 
     * @param country
     * @param city
     * @return
     *     returns net.restfulwebservices.datacontracts._2008._01.Weather
     * @throws IWeatherForecastServiceGetForecastByCityDefaultFaultContractFaultFaultMessage
     */
    @WebMethod(operationName = "GetForecastByCity", action = "GetForecastByCity")
    @WebResult(name = "GetForecastByCityResult", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
    @RequestWrapper(localName = "GetForecastByCity", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "net.restfulwebservices.servicecontracts._2008._01.GetForecastByCity")
    @ResponseWrapper(localName = "GetForecastByCityResponse", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "net.restfulwebservices.servicecontracts._2008._01.GetForecastByCityResponse")
    public Weather getForecastByCity(
        @WebParam(name = "City", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
        String city,
        @WebParam(name = "Country", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
        String country)
        throws IWeatherForecastServiceGetForecastByCityDefaultFaultContractFaultFaultMessage
    ;

}
