
package net.restfulwebservices.servicecontracts._2008._01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherForecastService", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", wsdlLocation = "file:/D:/jp/tpProjet/annee4/semestre3/webservices/weatherforecastservice/WeatherForecastService.wsdl")
public class WeatherForecastService
    extends Service
{

    private final static URL WEATHERFORECASTSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEATHERFORECASTSERVICE_EXCEPTION;
    private final static QName WEATHERFORECASTSERVICE_QNAME = new QName("http://www.restfulwebservices.net/ServiceContracts/2008/01", "WeatherForecastService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/jp/tpProjet/annee4/semestre3/webservices/weatherforecastservice/WeatherForecastService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERFORECASTSERVICE_WSDL_LOCATION = url;
        WEATHERFORECASTSERVICE_EXCEPTION = e;
    }

    public WeatherForecastService() {
        super(__getWsdlLocation(), WEATHERFORECASTSERVICE_QNAME);
    }

    public WeatherForecastService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERFORECASTSERVICE_QNAME, features);
    }

    public WeatherForecastService(URL wsdlLocation) {
        super(wsdlLocation, WEATHERFORECASTSERVICE_QNAME);
    }

    public WeatherForecastService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERFORECASTSERVICE_QNAME, features);
    }

    public WeatherForecastService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherForecastService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWeatherForecastService
     */
    @WebEndpoint(name = "BasicHttpBinding_IWeatherForecastService")
    public IWeatherForecastService getBasicHttpBindingIWeatherForecastService() {
        return super.getPort(new QName("http://www.restfulwebservices.net/ServiceContracts/2008/01", "BasicHttpBinding_IWeatherForecastService"), IWeatherForecastService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWeatherForecastService
     */
    @WebEndpoint(name = "BasicHttpBinding_IWeatherForecastService")
    public IWeatherForecastService getBasicHttpBindingIWeatherForecastService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.restfulwebservices.net/ServiceContracts/2008/01", "BasicHttpBinding_IWeatherForecastService"), IWeatherForecastService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERFORECASTSERVICE_EXCEPTION!= null) {
            throw WEATHERFORECASTSERVICE_EXCEPTION;
        }
        return WEATHERFORECASTSERVICE_WSDL_LOCATION;
    }

}
