
package com.ipr.db;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IPRConnectImplService", targetNamespace = "http://db.ipr.com/", wsdlLocation = "file:/D:/java/workspace/IPRClient/src/ipr.wsdl")
public class IPRConnectImplService
    extends Service
{

    private final static URL IPRCONNECTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IPRCONNECTIMPLSERVICE_EXCEPTION;
    private final static QName IPRCONNECTIMPLSERVICE_QNAME = new QName("http://db.ipr.com/", "IPRConnectImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/java/workspace/IPRClient/src/ipr.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IPRCONNECTIMPLSERVICE_WSDL_LOCATION = url;
        IPRCONNECTIMPLSERVICE_EXCEPTION = e;
    }

    public IPRConnectImplService() {
        super(__getWsdlLocation(), IPRCONNECTIMPLSERVICE_QNAME);
    }

    public IPRConnectImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IPRCONNECTIMPLSERVICE_QNAME, features);
    }

    public IPRConnectImplService(URL wsdlLocation) {
        super(wsdlLocation, IPRCONNECTIMPLSERVICE_QNAME);
    }

    public IPRConnectImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IPRCONNECTIMPLSERVICE_QNAME, features);
    }

    public IPRConnectImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IPRConnectImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPRConnect
     */
    @WebEndpoint(name = "IPRConnectImplPort")
    public IPRConnect getIPRConnectImplPort() {
        return super.getPort(new QName("http://db.ipr.com/", "IPRConnectImplPort"), IPRConnect.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPRConnect
     */
    @WebEndpoint(name = "IPRConnectImplPort")
    public IPRConnect getIPRConnectImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://db.ipr.com/", "IPRConnectImplPort"), IPRConnect.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IPRCONNECTIMPLSERVICE_EXCEPTION!= null) {
            throw IPRCONNECTIMPLSERVICE_EXCEPTION;
        }
        return IPRCONNECTIMPLSERVICE_WSDL_LOCATION;
    }

}
