
package com.cdyne.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Our system uses a multiple sources for resolution.  Including a host database, trace route information, and other systems.  Resolves IP addresses to Organization, Country, City, and State/Province, Latitude, Longitude.  In most US cities it will also provide some extra information such as Area Code, and more.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IP2Geo", targetNamespace = "http://ws.cdyne.com/", wsdlLocation = "file:/D:/jp/tpProjet/annee4/semestre3/webservices/wsdl/geoipcdyne.wsdl")
public class IP2Geo
    extends Service
{

    private final static URL IP2GEO_WSDL_LOCATION;
    private final static WebServiceException IP2GEO_EXCEPTION;
    private final static QName IP2GEO_QNAME = new QName("http://ws.cdyne.com/", "IP2Geo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/jp/tpProjet/annee4/semestre3/webservices/wsdl/geoipcdyne.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IP2GEO_WSDL_LOCATION = url;
        IP2GEO_EXCEPTION = e;
    }

    public IP2Geo() {
        super(__getWsdlLocation(), IP2GEO_QNAME);
    }

    public IP2Geo(WebServiceFeature... features) {
        super(__getWsdlLocation(), IP2GEO_QNAME, features);
    }

    public IP2Geo(URL wsdlLocation) {
        super(wsdlLocation, IP2GEO_QNAME);
    }

    public IP2Geo(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IP2GEO_QNAME, features);
    }

    public IP2Geo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IP2Geo(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IP2GeoSoap
     */
    @WebEndpoint(name = "IP2GeoSoap")
    public IP2GeoSoap getIP2GeoSoap() {
        return super.getPort(new QName("http://ws.cdyne.com/", "IP2GeoSoap"), IP2GeoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IP2GeoSoap
     */
    @WebEndpoint(name = "IP2GeoSoap")
    public IP2GeoSoap getIP2GeoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.cdyne.com/", "IP2GeoSoap"), IP2GeoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IP2GEO_EXCEPTION!= null) {
            throw IP2GEO_EXCEPTION;
        }
        return IP2GEO_WSDL_LOCATION;
    }

}
